version: "3.12"

services:
  67c76741b571491375522fd3_service:
    build: .
    container_name: 67c76741b571491375522fd3_container
    # Adjust your desired external port mapping here. For example:
    # "8502:8501" means the app is internally on 8501, but externally accessible on 8502.
    ports:
      - "8526:8501"
    environment:
      - PORT=8501  # This must match the internal port used by Streamlit
    restart: always
